home/urls.py
from django.urls import path
from .views import HomeV, lessondetail, lessonv, lecsv

app_name = "home"
urlpatterns = [
    path('', HomeV, name="home"),
    path('<int:id>', lessonv, name='lessons'),
    path('lesson/<int:id>', lessondetail, name='lesson'),
    path("lectures", lecsv, name="all")
    
]

pay/urls.py
from django.urls import path
from .views import token
app_name = 'pay'

urlpatterns = [
	path('', token, name='pay'),
]

reports/urls.py
from django.urls import path
from .views import homeworkrepfV, reportV, homeworkreportdetailV, examrebortfV, examreportdetailV

app_name = "reports"
urlpatterns = [
    path("homework/<int:id>", homeworkrepfV, name="homerf"),
    path("exam/<int:id>", examrebortfV, name="examrf"),
    path("report", reportV, name="report"),
    path("report/homework/<int:id>", homeworkreportdetailV, name="homerv"),
    path("report/exam/<int:id>", examreportdetailV, name="examrv"),
]

saskeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path("student/", include('students.urls', namespace="student")),
    path("task/", include('tasks.urls', namespace="task")),
    path("report/", include('reports.urls', namespace="reports")),
    path("pay/", include('pay.urls', namespace="pay")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

students/urls.py
from django.urls import path, include
from .views import joinV
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView, PasswordResetView, PasswordResetConfirmView

app_name = 'students'
urlpatterns = [
    path("", joinV, name='join'),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/",LogoutView.as_view(),name='logout'),
    path("changepassword/",PasswordChangeView.as_view(),name='change'),
    path("password_change_done/",PasswordChangeDoneView.as_view(),name='chdone'),
    path("reset/",PasswordResetView.as_view(),name='reset'),
    path("reset_conf/",PasswordResetConfirmView.as_view(),name='resetconf'),
]

tasks/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import homeworkV, examlistV, examquestV
app_name="tasks"

urlpatterns = [
    path("<int:id>", homeworkV, name="homework"),
    path("exams", login_required(examlistV.as_view()), name="exams"),
    path("exam/<int:id>", examquestV, name="exam")
]

templates/compindex/head.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static './bootstrap-css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './bootstrap-css/icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static './css/style.css' %}">
    

templates/compindex/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-warning" dir="rtl">
      <div class="container-fluid"><a class="navbar-brand" href="#">&#x627;&#x644;&#x62A;&#x641;&#x648;&#x642;</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">&#x627;&#x644;&#x631;&#x626;&#x64A;&#x633;&#x64A;&#x647;</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'home:all' %}">&#x627;&#x644;&#x634;&#x631;&#x62D;</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'task:exams' %}">&#x627;&#x644;&#x627;&#x645;&#x62A;&#x62D;&#x627;&#x646;&#x627;&#x62A;</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'reports:report' %}">&#x627;&#x644;&#x646;&#x62A;&#x627;&#x626;&#x62C;</a></li>
            {% if user.is_staff %}
            <li class="nav-item"><a class="nav-link" href="/admin">لوحة التحكم</a></li>
            {% endif %}
          </ul>
          {% if not user.is_staff %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown "><a class="nav-link" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-circle"></i></a>
              <ul class="dropdown-menu bg-warning" aria-labelledby="navbarDropdown">
                <li>
                  <h6 class="dropdown-item np" href="#">أسم الطالب:
                  <span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %}
                  > {{ cuser.Sfname }} {{ cuser.Smname }} {{ cuser.Slname }}  
                  </span></h6>
                </li>
                <li>
                  <h6 class="dropdown-item np" href="#"> الرقم القومي:<span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %} > {{ cuser.Sidnumber }} </span></h6>
                </li>
                <li>
                  <h6 class="dropdown-item np" href="#"> رقم المجموعه:<span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %} > {{ cuser.Sidgroup }} </span></h6>
                </li>
                <li>
                  <h6 class="dropdown-item np" href="#"> رصيد الطالب:<span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %} > {{ cuser.points }} </span><span class="usera me-5" style='color:green;'><a href={% url 'pay:pay' %}>أشحن الأن</a></span></h6>
                </li>
                <li>
                  <h6 class="dropdown-item np" href="#"> حالة الطالب:<span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %} > {% if cuser.points >= 10 %} <i class="bi bi-person-check-fill"></i> {% else %}<i class="bi bi-person-x-fill"></i> {% endif %}</span></h6>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'student:change' %}">تغيير كلمة المرور</a></li>
                <li><a class="dropdown-item" href="{% url 'reports:report' %}">التقرير</a></li>
                <li><a class="dropdown-item" href="{% url 'student:logout' %}">تسجيل الخروج </a></li>
              </ul>
            </li>
          </ul>
          {% endif %}
          {% if user.is_staff %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown "><a class="nav-link" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-bounding-box"></i></a>
              <ul class="dropdown-menu bg-warning" aria-labelledby="navbarDropdown">
                <li>
                  <h6 class="dropdown-item np" href="#"> أسم الاستاذ: <span class="usera"> {{ user.first_name }} {{ user.last_name }}</span>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'student:change' %}">تغيير كلمة المرور</a></li>
                <li><a class="dropdown-item" href="#">إعدادات </a></li>
                <li><a class="dropdown-item" href="{% url 'student:logout' %}">تسجيل الخروج </a></li>
              </ul>
            </li>
          </ul>
        {% endif %}
        </div>
      </div>
    </nav>