home/urls.py
from django.urls import path
from .views import HomeV, lessondetail, lessonv, lecsv

app_name = "home"
urlpatterns = [
    path('', HomeV, name="home"),
    path('<int:id>', lessonv, name='lessons'),
    path('lesson/<int:id>', lessondetail, name='lesson'),
    path("lectures", lecsv, name="all")
    
]

pay/urls.py
from django.urls import path
from .views import token
app_name = 'pay'

urlpatterns = [
	path('', token, name='pay'),
]

saskeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path("student/", include('students.urls', namespace="student")),
    path("task/", include('tasks.urls', namespace="task")),
    path("report/", include('reports.urls', namespace="reports")),
    path("pay/", include('pay.urls', namespace="pay")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import homeworkV, examlistV, examquestV
app_name="tasks"

urlpatterns = [
    path("<int:id>", homeworkV, name="homework"),
    path("exams", login_required(examlistV.as_view()), name="exams"),
    path("exam/<int:id>", examquestV, name="exam")
]

home/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _



class Lessons(models.Model):
    def upleson(self, filename):
        name = filename.split(".")
        return "lessons/%s.%s" %(self.name, name[-1])
    name = models.CharField(_("اسم الحصه"),max_length=256)
    catname = models.ForeignKey("home.catgory", verbose_name=_("يتبع"), on_delete=models.PROTECT, null=True, blank=True)
    date = models.DateField(_("تاريخ الحصه"), auto_now_add=True)
    video = models.FileField(_("الحصه"), upload_to=upleson, max_length=100)

    def __str__(self):
        return f'{self.id}- {self.name}, من فرع {self.catname}'
    class Meta:
        verbose_name = "الدرس"
        verbose_name_plural = "الدروس"


class catgory(models.Model):
    name = models.CharField(_("اسم التصنيف"), max_length=50)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "الفرع"
        verbose_name_plural = "الفروع"
        

home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Lessons, catgory
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from students.models import student
# Create your views here.

@login_required
def HomeV(request):
    context={
        "cats":catgory.objects.all(),
    }
    return render(request, "index.html", context)


@login_required
def lessonv(request, id):
    if not request.user.is_staff:
        cuser = student.objects.get(sinit=request.user)
        cat = catgory.objects.get(id=id)
        lessons = Lessons.objects.filter(catname=cat)
    if request.user.is_staff:
        cat = catgory.objects.get(id=id)
        lessons = Lessons.objects.filter(catname = cat)
    
    context={
        "les":lessons,
        "cat":cat
    }
    return render(request, "lessons.html", context)

@login_required
def lessondetail(request, id):
    
    if not request.user.is_staff:
        cuser = student.objects.get(sinit=request.user)
        if Lessons.objects.filter(id = id).exists:
            lesvisit = Lessons.objects.get(id = id)
        if cuser.points < 10 :
            if lesvisit in cuser.watchedlecs.all():
                lesvisit = lesvisit
            else:
                lesvisit = []
        if cuser.points >= 10 and lesvisit not in cuser.watchedlecs.all():
            lesvisit = Lessons.objects.get(id = id)
            cuser.watchedlecs.add(lesvisit)
            cuser.points = cuser.points - 10
            cuser.save()
    else:
        lesvisit = Lessons.objects.get(id = id)
    

    context={
        "lesson": lesvisit,
    }
    return render(request, "lesson.html", context)


@login_required
def lecsv(request):
    if not request.user.is_staff:
        cuser = student.objects.get(sinit=request.user)
        lessons = Lessons.objects.all()
    if request.user.is_staff:
        lessons = Lessons.objects.all()
    context={
        "all" : lessons
    }
    return render(request, "lecs.html", context)



def handel400(request, exception):
    return render(request, "400.html", status=400)

def handel403(request, exception):
    return render(request, "403.html", status=403)

def handel404(request, exception):
    return render(request, "404.html", status=404)

def handel500(request, exception):
    return render(request, "500.html", status=500)

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<title>
  {% block title %}
  مركز التفوق | الرئيسيه
  {% endblock title %}
</title>
{% block head %}
  {% include './compindex/head.html' %}
  {% block spstyle %}
    
  {% endblock spstyle %}
{% endblock head %}
</head>
<body>
    {% block nav %}
      {% include './compindex/nav.html' %}
    {% endblock nav %}
    <div class="container">
      {% if user.is_staff %} 
        {% block test %} <h1 class="alert alert-info">انت تشاهد وضع تجريبي كطالب </h1> {% endblock test %}
      {% endif %}
      {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="message alert alert-{{ message.tags }}" {% endif %} >{{ message }}</li>
            {% endfor %}
        </ul>
      {% endif %}
    {% block main %}
      <header> 
        <h6>{% if user.is_staff %} {{user}} {% else %}  {{cuser}} {% endif %}</h6>
        <h1 class="ht">
          مرحبا بك يا  {% if user.is_staff %} {{user.first_name}} {% else %}  {{cuser.Sfname}} {% endif %}  في مركزنا التعليمي
        </h1>
      </header>
      {% if cats %}
        <main class="center"> 
          <div class="row">
            {% for cat in cats %}
              <a class="catlink col-md-3 me-auto ms-auto"  href="{% url 'home:lessons' cat.id %}">
                <div>
                  <h1 class="catname">{{ cat.name }}</h1>
                </div>
              </a>
            {% endfor %}
            </div>
        </main>
        {% else %}
          <h2 class="alert alert-info">لم يتم نشر اي محاضرات بعد</h2>
      {% endif %}
    {% endblock main %}
      <hr>
      <footer> 
        <div class="row justify-content-center me-auto"> 
          <div class="col-md-3 "> 
            <h2>عن التفوق</h2>
            <p>مركز التفوق التعليمي معنا انتم متفوقون دائماً </p>
          </div>
          <div class="links col-md-3 col-sm-5"> 
            <h2>الروابط</h2>
            <ul class="links-info"> 
              <li> <a href="#"><i class="bi bi-facebook"></i></a></li>
              <li> <a href="#"><i class="bi bi-youtube"></i></a></li>
              <li> <a href="#"><i class="bi bi-instagram"></i></a></li>

            </ul>
          </div>
          <div class="our col-md-3 col-sm-12"> 
            <h2>التواصل</h2>
            <ul> 
              <li> <a class="phone-link" href="#">0106098474 <i class="bi bi-phone-fill"></i> </a></li>
              <li> <a class="phone-link" href="#">0106098474 <i class="bi bi-telephone-fill"></i> </a></li>
            </ul>
          </div>
        </div>
        <hr>
        <div id="sas"> 
          <h6>&copy; 2021 copyright for <a href="https://www.facebook.com/SASKE.Company" class="sac">SACODY</a> SASKE Company</h6>
        </div>
      </footer>
    </div>
      {% block script %}
      <script src="{% static './js/query.js' %}"> </script>
      <script src="{% static './scripts/index.js' %}"> </script>
      <script src="{% static './bootstrap-js/bootstrap.esm.min.js' %}"></script>
      <script src="{% static './bootstrap-js/bootstrap.min.js' %}"></script>
      {% endblock script %}
      {% block spscript  %}{% endblock spscript  %}
  </body>
</html>

home/templates/home/lecs.html
{% extends 'index.html' %}
{% block title %}
    مركز التفوق | المحاضرات
{% endblock title %}
{% block main %}
<header>
    <h6>{% if user.is_staff %} {{user}} {% else %} {{cuser}} {% endif %} </h6>
    <h1 class="htc">
        مرحبا بك يا {% if user.is_staff %} {{user.first_name}} {% else %} {{cuser.Sfname}} {% endif %} في مركزنا
        التعليمي
    </h1>
</header>
{% if all %}
<h2>المحاضرات المتاحه:</h2>
<hr style="height:5px;" class="bg-warning">
<div class="row">
    {% for all in all %}
    <div class="col-md-4 me-auto ms-auto sec">
        <a class="lec1" href="{% url 'home:lesson' all.id %}">
            <div class="lec"></div>
            <div class="lec-info">
                <h1 class="lecid">{{ all.id }}</h1>
                <p class="lecname" {% if all in cuser.watchedlecs.all %} style="color: red;" {% else %} style="color: black;" {% endif %}>{{ all.name }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% else %}
<h2 class="alert alert-info">لم يتم نشر اي محاضرات بعد</h2>
{% endif %}
{% endblock main %}

{% block spstyle %}
    <script>
        window.addEventListener("load", function(){
            document.querySelectorAll(".nav-link")[0].classList.remove("active")
            document.querySelectorAll(".nav-link")[1].classList.add("active")
        });
    </script>
{% endblock spstyle %}

home/templates/home/lesson.html
{% extends 'index.html' %}
<title>
  {% block title %}
  مركز التفوق | محاضره 
  {% endblock title %}
</title>
{% block main %}
  <header>
    <h1 class="ht">
      مرحبا بك يا {% if cuser.username %}{{cuser.username}} {% else %} {{cuser.Sfname}} {% endif %} في مركزنا التعليمي
    </h1>
  </header>
  {% if lesson %}
    <div class="lesson">
      <div class="lesson-info">
        <h1>المحاضره رقم {{ lesson.id }}</h1>
        <hr>
        <video id="lessonvideo" controls>
          <source src="{{ lesson.video.url }}" type="video/mp4">
          <source src="{{ lesson.video.url }}" type="video/mp4">
          Your browser does not support the video element.
        </video>
      </div>
    </div>
    <hr style="height:10px; background-color:green;">
    <a class="homelink" href="{% url 'task:homework' lesson.id %}">
      <div id="homebox">
        <h1> الواجب المنزلي لدرس {{ lesson.name }} </h1>
      </div>
    </a>
    </div>
  {% else %}
    <div class="lesson">
      <div class="lesson-info">
        <h1 style="color:red">نأسف لا يمكننا عرض هذه الحصه</h1>
        <hr>
        <h3>سيكون بإمكانك مشاهدة هذه الحلقه بعد إعادة شحن رصيدك</h3>
      </div>
    </div>
    </div>
  {% endif %}
{% endblock main %}

{% block spstyle %}
  <script>
    window.addEventListener("load", function(){
        document.querySelectorAll(".nav-link")[0].classList.remove("active");
        document.querySelectorAll(".nav-link")[1].classList.add("active");
    });
  </script>
{% endblock spstyle %}

home/templates/home/lessons.html
{% extends 'index.html' %}
{% block main %}
<header> 
    <h6>{% if user.is_staff %} {{user}} {% else %}  {{cuser}} {% endif %}</h6>
    <h1 class="ht">
    مرحبا بك يا  {% if user.is_staff %} {{user.first_name}} {% else %}  {{cuser.Sfname}} {% endif %}  في مركزنا التعليمي
    </h1>
</header>
<h2 >محاضرات فرع ال{{ cat.name }}:</h2>
<hr style="height:5px;" class="bg-warning">
<div class="row">
{% if les %}
    {% if not user.is_staff %}
            {% for les in les %}
                <div class="col-md-3 me-auto ms-auto  sec"> 
                    <a class="lec1" href="{% url 'home:lesson' les.id %}">
                        <div class="lec">
                        </div>
                            <div class="lec-info">
                                <h1 class="lecid">{{ les.id }}</h1>
                                <p class="lecname" {% if les in cuser.watchedlecs.all %} style="color: red;" {% else %} style="color: black;" {% endif %}>{{ les.name }}</p>
                            </div>
                    </a>
                </div>  
            {% endfor %}
    {% endif %}
    {% if user.is_staff %}
        {% for les in les %}
            <div class="col-md-3 me-auto ms-auto  sec"> 
                <a class="lec1" href="{% url 'home:lesson' les.id %}">
                    <div class="lec"></div>
                    <div class="lec-info">
                        <h1 class="lecid">{{ les.id }}</h1>
                        <p class="lecname">{{ les.name }}</p>
                    </div>
                </a>
            </div>  
        {% endfor %}
    {% endif %}
{% endif %}
{% if not les %}
    <h2 class="alert alert-info">لم يتم نشر اي محاضرات بعد</h2>
{% endif %}
</div>
{% endblock main %}

{% block spstyle %}
    <script>
        window.addEventListener("load", function(){
            document.querySelectorAll(".nav-link")[0].classList.remove("active")
            document.querySelectorAll(".nav-link")[1].classList.add("active")
        });
    </script>
{% endblock spstyle %}