pay/urls.py
from django.urls import path
from .views import token
app_name = 'pay'

urlpatterns = [
	path('', token, name='pay'),
]

reports/urls.py
from django.urls import path
from .views import homeworkrepfV, reportV, homeworkreportdetailV, examrebortfV, examreportdetailV

app_name = "reports"
urlpatterns = [
    path("homework/<int:id>", homeworkrepfV, name="homerf"),
    path("exam/<int:id>", examrebortfV, name="examrf"),
    path("report", reportV, name="report"),
    path("report/homework/<int:id>", homeworkreportdetailV, name="homerv"),
    path("report/exam/<int:id>", examreportdetailV, name="examrv"),
]

saskeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path("student/", include('students.urls', namespace="student")),
    path("task/", include('tasks.urls', namespace="task")),
    path("report/", include('reports.urls', namespace="reports")),
    path("pay/", include('pay.urls', namespace="pay")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reports/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models

# Create your models here.
class report(models.Model):
    user = models.ForeignKey("auth.User", verbose_name=_("الطالب"), on_delete=models.CASCADE, null=True, blank=True)
    homerport = models.ManyToManyField("homeworkReport", verbose_name=_("واجبات الطالب"), blank=True)
    examReport = models.ManyToManyField("examReport", verbose_name=_("امتحانات الطالب"), blank=True)
    
    def __str__(self):
        return f"تقرير {self.user}"
    class Meta:
        verbose_name = "التفرير"
        verbose_name_plural = "التقارير"
class homeworkReport(models.Model):
    user = models.ForeignKey("auth.User", verbose_name=_("الطالب"), on_delete=models.CASCADE, null=True, blank=True)
    lesson = models.ForeignKey("home.Lessons", verbose_name=_("واجب درس"), on_delete=models.CASCADE)
    asknumber = models.IntegerField(_("عدد الاسئله"), null=True, blank=True)
    correctAnswers = models.IntegerField(_("الاجابات الصحيحه"), null=True, blank=True)
    wrongAnswers = models.IntegerField(_("الإجابات الخاطئه"), null=True, blank=True)
    presentage = models.IntegerField(_("النسبه المئويه"),null=True, blank=True,)
    class Meta:
        ordering = ['id']
    def __str__(self):
        return f"تقرير الواجب المنزلي {self.lesson} للطالب {self.user} "
    class Meta:
        verbose_name = "تفرير الواجب"
        verbose_name_plural = "تقاربر الواجب"



class examReport(models.Model):
    user = models.ForeignKey("auth.User", verbose_name=_("الطالب"), on_delete=models.CASCADE, null=True, blank=True)
    exam = models.ForeignKey("tasks.exam", verbose_name=_("امتحان"), on_delete=models.CASCADE)
    asknumber = models.IntegerField(_("عدد الاسئله"), null=True, blank=True)
    correctAnswers = models.IntegerField(_("الاجابات الصحيحه"), null=True, blank=True)
    wrongAnswers = models.IntegerField(_("الإجابات الخاطئه"), null=True, blank=True)
    presentage = models.IntegerField(_("النسبه المئويه"),null=True, blank=True)
    class Meta:
        ordering = ['id']
    def __str__(self):
        return f"تقرير {self.exam} للطالب {self.user} "
    
    class Meta:
        verbose_name = "تقرير الامتحان"
        verbose_name_plural = "تقارير الامتحانات"

reports/views.py
from django import urls
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.urls.conf import path
from .models import examReport, homeworkReport, report
from django.contrib.auth.models import User
from students.models import student
from home.models import Lessons
from tasks.models import exam
from django.contrib.auth.decorators import login_required
# Create your views here.

def homeworkrepfV(request, id):
    if not request.user.is_staff:
        cuser = request.user
        user = User.objects.get(username=cuser)
        lesson = Lessons.objects.get(id = id)
        if request.POST["questions"]==None or request.POST["questions"]=="":
            questionNumber = 0
        else:
            questionNumber = int(request.POST["questions"])
        if request.POST["result"]==None or request.POST["result"]=="" :
            correctNumbers = 0
        else:
            correctNumbers = request.POST["result"]
        if request.POST["wrong"]==None or request.POST["wrong"]=="":
            wrongNumbers = 0
        else:
            wrongNumbers = request.POST["wrong"]
        if request.POST['present']==None or request.POST['present']=="":
            req = 0
        else:
            req = request.POST["present"]
        cstudent = student.objects.get(sinit=user)
        present = int(req[0:-1])
        try : int(wrongNumbers)
        except ValueError:
            wrongNumbers = 0
        if type(questionNumber) == int and type(correctNumbers) == int:
            questionNumber = int(questionNumber)
            correctNumbers = int(correctNumbers)
        rephomework = homeworkReport(
                                user=user,
                                lesson=lesson,
                                asknumber=questionNumber,
                                correctAnswers=correctNumbers,
                                presentage=present,
                                wrongAnswers=wrongNumbers
                                )
        rephomework.save()
        cstudent.finishedHomework.add(lesson)
        if not report.objects.filter(user=request.user):
            rep = report(
                user=user,
            )
            rep.save()
        else:
            rep = report.objects.get(user=request.user)
        rep.homerport.add(rephomework)
        cstudent.shomeworks = (cstudent.shomeworks + rephomework.presentage)
        cstudent.Spercenthomeworks = cstudent.shomeworks / (len(cstudent.finishedHomework.all()))
        cstudent.save()
        messages.success(request, 'تم إرسال اجاباتك بنجاح')
    if request.user.is_staff:
        messages.info(request, "لا يمكنك ارسال هذه المعلومات انت في وضع تجريبي الأن")    
    return redirect("home:lesson", id=id)   

def examrebortfV(request, id):
    if not request.user.is_staff:
        cuser = request.user
        user = User.objects.get(username=cuser)
        cexam = exam.objects.get(id=id)
        if request.POST["questions"]==None or request.POST["questions"]=="":
            questionNumber = 0
        else:
            questionNumber = int(request.POST["questions"])
        if request.POST["result"]==None or request.POST["result"]=="" :
            correctNumbers = 0
        else:
            correctNumbers = request.POST["result"]
        if request.POST["wrong"]==None or request.POST["wrong"]=="":
            wrongNumbers = 0
        else:
            wrongNumbers = request.POST["wrong"]
        if request.POST['present']==None or request.POST['present']=="":
            req = 0
        else:
            req = request.POST["present"]
        cstudent = student.objects.get(sinit=user)
        if req == None or req == "":
            req = 0
            present = int(req)
        else:
            present = int(req)
        try : int(wrongNumbers)
        except ValueError:
            wrongNumbers = 0
        if type(questionNumber) == int and type(correctNumbers) == int:
            questionNumber = int(questionNumber)
            correctNumbers = int(correctNumbers)
        repexamreport = examReport(
                                user=user,
                                exam=cexam,
                                asknumber=questionNumber,
                                correctAnswers=correctNumbers,
                                presentage=present,
                                wrongAnswers=wrongNumbers
                                )
        repexamreport.save()
        cstudent.finishExam.add(cexam)
        if not report.objects.filter(user=request.user):
            rep = report(
                user=user,
            )
            rep.save()
        else:
            rep = report.objects.get(user=request.user)
        rep.examReport.add(repexamreport)
        cstudent.sexams = (cstudent.sexams + repexamreport.presentage)
        cstudent.Spercentexams = (cstudent.sexams) / len(cstudent.finishExam.all())
        cstudent.save()
        messages.success(request, 'تم إرسال اجاباتك بنجاح')
    if request.user.is_staff:
        messages.info(request, "لا يمكنك ارسال هذه المعلومات انت في وضع تجريبي الأن")    
    return redirect("task:exams")   

@login_required
def reportV(request):
    if not request.user.is_staff and report.objects.filter(user = request.user).exists():
        cstudent = student.objects.get(sinit=request.user)
        if homeworkReport.objects.filter(user=request.user) and examReport.objects.filter(user=request.user).exists( ):
            cstudent.Spercent = (cstudent.Spercentexams + cstudent.Spercenthomeworks) / 2
        else:
            cstudent.Spercent = (cstudent.Spercentexams + cstudent.Spercenthomeworks)
        cstudent.save()
        percent = cstudent.Spercent
        if homeworkReport.objects.filter(user=request.user).exists():
            rep = report.objects.get(user = request.user)
            hrep = homeworkReport.objects.filter(user=request.user)
        else:
            rep=""
            hrep=""

        if examReport.objects.filter(user=request.user).exists( ):
            rep = report.objects.get(user = request.user)
            erep = examReport.objects.filter(user=request.user)
        else:
            erep=""

    else:
        rep=""
        hrep=""
        erep=""
        percent=""
    
    context={
    "rep": rep,
    "hrep": hrep,
    "erep": erep,
    "per": percent,
    }
    return render(request, "report.html", context)

def homeworkreportdetailV(request, id):
    if not request.user.is_staff:
        lesson = Lessons.objects.get(id=id)
        rep = homeworkReport.objects.get(lesson = lesson, user=request.user)
    if request.user.is_staff:
        rep = ""
    context={
        "rep": rep
    }
    return render(request, "homeworkreport.html", context)

@login_required
def examreportdetailV(request, id):
    if not request.user.is_staff and examReport.objects.filter(id=id).exists():
        rep = examReport.objects.get(user=request.user, id=id)
    if request.user.is_staff:
        rep = ""
    context={
        "rep": rep
    }
    return render(request, "homeworkreport.html", context)

reports/templates/reports/examreport.html
{% extends 'index.html' %}
{% load static %}
{% block spstyle %}
    <link rel="stylesheet" type="text/css" href="{% static './report/style/report.css' %}" />
{% endblock spstyle %}
{% block main %}
    <header> 
    <h6>{{ cuser }}</h6>
    <h1 class="ht">
      مرحبا بك يا  {% if cuser.is_staff %} {{cuser.first_name}} {% else %}  {{cuser.Sfname}} {% endif %}  في مركزنا التعليمي
    </h1>
  </header>
  <div>
    <h3>{{ rep }}</h3>
    <hr style="background-color: #ffc107; height: .25rem;">
    <h1 class="percent-tit">النسبه المئويه</h1>
    <div class="homewrep-container mb-3 mt-3">
        <div class="homewrep">
            <div class="chart" data-percent="{{rep.presentage}}"><span class="percent"></span></div>
        </div>
    </div>
    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th>عدد الاسئله</th>
                <th>عدد الإجابات الصحيحه</th>
                <th>عدد الإجابات الخاطئه</th>
                <th>الدرجه الكليه</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{rep.asknumber}}</td>
                <td>{{rep.correctAnswers}}</td>
                <td>{{rep.wrongAnswers}}</td>
                <td>{{rep.correctAnswers}} / {{rep.asknumber}}</td>
            </tr>
        </tbody>
    </table>
    <div>
        <i class="{% if rep.presentage >= 50 %} bi bi-check-circle-fill {% else %} bi bi-x-circle-fill {% endif %}" style="position: fixed; top: 25%; left: 10%; font-size: 150px; color: {% if rep.presentage > 50 %} green {% else %} red; {% endif %}"></i>
    </div>
  </div>
{% endblock main %}

{% block spscript %}
    <script>
        window.addEventListener("load", function(){
            document.querySelectorAll(".nav-link")[0].classList.remove("active");
            document.querySelectorAll(".nav-link")[3].classList.add("active");
        });
  </script>
    <script src="{% static './report/script/jquery.easypiechart.min.js' %}"></script>
    <script src="{% static './report/script/report.js' %}"></script>
{% endblock spscript %}

reports/templates/reports/homeworkreport.html
{% extends 'index.html' %}
{% load static %}
{% block spstyle %}
    <link rel="stylesheet" type="text/css" href="{% static './report/style/report.css' %}" />
{% endblock spstyle %}
{% block main %}
    <header> 
    <h6>{{ cuser }}</h6>
    <h1 class="ht">
      مرحبا بك يا  {% if cuser.is_staff %} {{cuser.first_name}} {% else %}  {{cuser.Sfname}} {% endif %}  في مركزنا التعليمي
    </h1>
  </header>
  <div>
    <h3>{{ rep }}</h3>
    <hr style="background-color: #ffc107; height: .25rem;">
    <h1 class="percent-tit">النسبه المئويه</h1>
    <div class="homewrep-container mb-3 mt-3">
        <div class="homewrep">
            <div class="chart" data-percent="{{rep.presentage}}"><span class="percent"></span></div>
        </div>
    </div>
    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th>عدد الاسئله</th>
                <th>عدد الإجابات الصحيحه</th>
                <th>عدد الإجابات الخاطئه</th>
                <th>الدرجه الكليه</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{rep.asknumber}}</td>
                <td>{{rep.correctAnswers}}</td>
                <td>{{rep.wrongAnswers}}</td>
                <td>{{rep.correctAnswers}} / {{rep.asknumber}}</td>
            </tr>
        </tbody>
    </table>
    <div>
        <i class="{% if rep.presentage >= 50 %} bi bi-check-circle-fill {% else %} bi bi-x-circle-fill {% endif %}" style="position: fixed; top: 25%; left: 10%; font-size: 150px; color: {% if rep.presentage > 50 %} green {% else %} red; {% endif %}"></i>
    </div>
  </div>
{% endblock main %}

{% block spscript %}
    <script>
        window.addEventListener("load", function(){
            document.querySelectorAll(".nav-link")[0].classList.remove("active");
            document.querySelectorAll(".nav-link")[3].classList.add("active");
        });
    </script>
    <script src="{% static './report/script/jquery.easypiechart.min.js' %}"></script>
    <script src="{% static './report/script/report.js' %}"></script>
{% endblock spscript %}

reports/templates/reports/report.html
{% extends 'index.html' %}
{% load static %}
{% block spstyle %}
    <link rel="stylesheet" type="text/css" href="{% static './report/style/report.css' %}" />

{% endblock spstyle %}
{% block main %}
{% if not user.is_staff %}
    <header> 
        <h6>{{ cuser }}</h6>
        <h1 class="ht">
        تقرير شامل للطالب   {% if cuser.is_staff %} {{cuser.first_name}} {% else %}  {{cuser.Sfname}} {% endif %}
        </h1>
  </header>
    <div class="repbox">
        <div class="homewrep-container " >
            <div class="homewrep">
                <div class="chart" data-percent="{% if per %}{{per}}%{% else %}0%{% endif %}"><span class="percent"></span></div>
            </div>
        </div>
        <div>
            <ul class="box-info-student">
                <li>
                <h4 class="dropdown-item np">أسم الطالب:
                <span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %}
                > {{ cuser.Sfname }} {{ cuser.Smname }} {{ cuser.Slname }}  
                </span></h6>
                </li>
                <li>
                <h4 class="dropdown-item np"> الرقم القومي:<span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %} > {{ cuser.Sidnumber }} </span></h6>
                </li>
                <li>
                <h4 class="dropdown-item np"> رقم المجموعه:<span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %} > {{ cuser.Sidgroup }} </span></h6>
                </li>
                <li>
                <h4 class="dropdown-item np" href="#"> رصيد الطالب:<span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %} > {{ cuser.points }} </span><span class="usera me-5" style='color:green;'><a href={% url 'pay:pay' %}>أشحن الأن</a></span></h4>
                </li>
                <li>
                <h4 class="dropdown-item np"> حالة الطالب:<span class="usera" {% if cuser.points >= 10 %} style='color:green;'; {% else %} style='color:red;' {% endif %} > {% if cuser.points >= 10 %} <i class="bi bi-person-check-fill"></i> {% else %}<i class="bi bi-person-x-fill"></i> {% endif %}</span></h6>
                </li>
            </ul>
        </div>
    </div>
    <hr style="height: 5px; color: green;">
    <div>
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  تفرير واجبات الطالب {{cuser.Sfname}}
                </button>
              </h2>
              <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                  <ol class="list-group list-group-item list-group-item-action list-group-numbered">
                      {% if hrep %}
                        {% for hrep in hrep %}
                        <li><a href="{% url 'reports:homerv' hrep.lesson_id %}">تقرير واجب {{ hrep.lesson }}</a></li>
                        {% endfor %}
                      {% else %}
                          <h2 class="alert alert-info" >لم تقم بحل اي واجب بعد</h2>
                      {% endif %}
                  </ol>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    تفرير امتحانات الطالب {{cuser.Sfname}}
                </button>
              </h2>
              <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <ol class="list-group list-group-item list-group-item-action list-group-numbered">
                        {% if erep %}
                          {% for erep in erep %}
                          <li><a href="{% url 'reports:examrv' erep.id %}">تقرير {{ erep.exam }}</a></li>
                          {% endfor %}
                        {% else %}
                        <h2 class="alert alert-info" >لم تقم بأداء اي امتحان بعد</h2>
                        {% endif %}
                    </ol>
                  </div>
              </div>
            </div>
        </div>
    </div>
{% endif %}




  {%if user.is_staff %}
    <header> 
        <h6>{{ user }}</h6>
        <h1 class="ht">
        تقرير شامل كوضع تجريبي    {{user.first_name}}
        </h1>
    </header>
  <div class="repbox">
    <div class="homewrep-container " >
        <div class="homewrep">
            <div class="chart" data-percent="90"><span class="percent"></span></div>
        </div>
    </div>
    <div>
        <ul class="box-info-student">
            <li>
              <h4 class="dropdown-item np">أسم الطالب:
              <span class="usera" style="color:green;";
              > {{ user.first_name }} {{ user.last_name }}
              </span></h6>
            </li>
            <li>
              <h4 class="dropdown-item np"> الرقم القومي:<span class="usera" style="color:green;"; >12345678901234 </span></h6>
            </li>
            <li>
              <h4 class="dropdown-item np"> رقم المجموعه:<span class="usera" style="color:green;"; > 1d </span></h6>
            </li>
            <li>
              <h4 class="dropdown-item np"> حالة تجريبيه:<span class="usera" style="color:green;"; > <i class="bi bi-person-check-fill"></i> </span></h6>
            </li>
          </ul>
    </div>
  </div>
  {% endif %}
{% endblock main %}
{% block spscript %}
    <script>
      window.addEventListener("load", function(){
        document.querySelectorAll(".nav-link")[0].classList.remove("active");
        document.querySelectorAll(".nav-link")[3].classList.add("active");
    });
    </script>
    <script src="{% static './report/script/jquery.easypiechart.min.js' %}"></script>
    <script src="{% static './report/script/report.js' %}"></script>
{% endblock spscript %}