home/urls.py
from django.urls import path
from .views import HomeV, lessondetail, lessonv, lecsv

app_name = "home"
urlpatterns = [
    path('', HomeV, name="home"),
    path('<int:id>', lessonv, name='lessons'),
    path('lesson/<int:id>', lessondetail, name='lesson'),
    path("lectures", lecsv, name="all")
    
]

pay/urls.py
from django.urls import path
from .views import token
app_name = 'pay'

urlpatterns = [
	path('', token, name='pay'),
]

reports/urls.py
from django.urls import path
from .views import homeworkrepfV, reportV, homeworkreportdetailV, examrebortfV, examreportdetailV

app_name = "reports"
urlpatterns = [
    path("homework/<int:id>", homeworkrepfV, name="homerf"),
    path("exam/<int:id>", examrebortfV, name="examrf"),
    path("report", reportV, name="report"),
    path("report/homework/<int:id>", homeworkreportdetailV, name="homerv"),
    path("report/exam/<int:id>", examreportdetailV, name="examrv"),
]

saskeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="home")),
    path("student/", include('students.urls', namespace="student")),
    path("task/", include('tasks.urls', namespace="task")),
    path("report/", include('reports.urls', namespace="reports")),
    path("pay/", include('pay.urls', namespace="pay")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import homeworkV, examlistV, examquestV
app_name="tasks"

urlpatterns = [
    path("<int:id>", homeworkV, name="homework"),
    path("exams", login_required(examlistV.as_view()), name="exams"),
    path("exam/<int:id>", examquestV, name="exam")
]

tasks/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class task(models.Model):
    def askimgupload(self, filename):
        file , ext = filename.split(".")
        return f"ask{self.lesson}/{file}.{ext}"
    answers = [
        ("1","الاجابه الاولي"),
        ("2","الاجابه الثانيه"),
        ("3","الاجابه الثالثه"),
        ("4","الاجابه الرابعه"),
        ]
    quest = models.TextField(_("السؤال"),null=True, blank=True)
    questimg = models.ImageField(_("صورة السؤال"), upload_to=askimgupload, height_field=None, width_field=None, max_length=None, null=True, blank=True)
    lesson = models.ForeignKey("home.Lessons", verbose_name=_("الدرس المتعلق"), on_delete=models.CASCADE, null=True, blank=True)
    exam = models.ForeignKey("tasks.exam", verbose_name=_('امتحان'), on_delete=models.CASCADE, null=True, blank=True)
    answer1 = models.CharField(_("الاجابه الاولي"), max_length=50, null=True, blank=True)
    answer2 = models.CharField(_("الاجابه الثانيه"), max_length=50, null=True, blank=True)
    answer3 = models.CharField(_("الاجابه الثالثه"), max_length=50, null=True, blank=True)
    answer4 = models.CharField(_("الاجابه الرابعه"), max_length=50, null=True, blank=True)
    answer = models.CharField(_("الاجابه الصحيحه"), max_length=50, choices=answers, null=True, blank=True)
    class Meta:
        verbose_name = "الأسئله"
        verbose_name_plural = "الأسئله"
class exam(models.Model):
    title = models.CharField(_("عنوان الامتحان"), max_length=256)
    publishAt = models.DateTimeField(_("التاريخ"), auto_now=True)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "امتحان"
        verbose_name_plural = "الإمتحانات"

tasks/views.py
from typing import List
from django.db import models
from django.shortcuts import render
from home.views import lessonv
from students.models import student
from .models import task, exam
from home.models import Lessons
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def homeworkV(request, id):
    if not request.user.is_staff:
        cuser = User.objects.get(username=request.user)
        lesson = Lessons.objects.get(id=id)
        cstudent = student.objects.get(sinit = cuser)
        finishHomeWork = cstudent.finishedHomework.filter(id=id)
        ask = task.objects.filter(lesson=lesson)

        context={
            "ask":ask,
            "les":lesson,
            "flesh":finishHomeWork
        }
    if request.user.is_staff:
        lesson = Lessons.objects.get(id=id)
        ask = task.objects.filter(lesson=lesson)
        context={
            "ask":ask,
            "les":lesson,
        }
    return render(request, "homeworks.html", context)


class examlistV(ListView):
    model= exam
    template_name = "exams.html"
    context_object_name = "exams"





@login_required
def examquestV(request, id):
    if not request.user.is_staff:
        cstudent = student.objects.get(sinit=request.user)
        guid = exam.objects.get(id = id)
        examquest = task.objects.filter(exam=guid)
        finish = cstudent.finishExam.filter(title=guid)
    if request.user.is_staff:
        guid = exam.objects.get(id = id)
        examquest = task.objects.filter(exam=guid)
        finish=""
    context = {
        "quest":examquest,
        "exam":guid,
        "finish":finish
    }
    return render(request, "exam.html", context)

tasks/templates/tasks/exam.html
{% extends 'index.html' %}

{% block main %}
    <div id="exam">
        <h2 class="mt-3" style="text-align:center; text-decoration:underline;" >{{ exam }}</h2>
        <h3 id="clock"></h3>
        <hr style="height:5px;" class="bg-warning">
        {% if not user.is_staff %}
                {% if not finish %}
                    {% if quest %}
                    <ol id="exam-body">
                        {% for quest in quest %}
                        <li>
                            <div id="quest" class="quest{{quest.id}}">
                                {% if not quest.questimg %}
                                    <h3 class="ask">{{ quest.quest }}</h3>
                                {% else %}
                                    <img id="questimg" src="{{ quest.questimg.url }}" alt="{{quest}}" width="100%" />
                                {% endif %}
                                {% if quest.quest %}
                                    <div id="questbttns">
                                        {% if quest.answer1 %}<button class="bttn btn btn-outline-warning" onclick="answer(1, {{ quest.id }})">{{ quest.answer1 }}</button> {% else %}<button id="an" class="bttn btn btn-outline-warning" onclick="answer(1, {{ quest.id }})"></button>{% endif %}
                                        {% if quest.answer2 %}<button class="bttn btn btn-outline-warning" onclick="answer(2, {{ quest.id }})">{{ quest.answer2 }}</button> {% else %}<button id="an" class="bttn btn btn-outline-warning" onclick="answer(2, {{ quest.id }})"></button>{% endif %}
                                        {% if quest.answer3 %}<button class="bttn btn btn-outline-warning" onclick="answer(3, {{ quest.id }})">{{ quest.answer3 }}</button> {% else %}<button id="an" class="bttn btn btn-outline-warning" onclick="answer(3, {{ quest.id }})"></button>{% endif %}
                                        {% if quest.answer4 %}<button class="bttn btn btn-outline-warning" onclick="answer(4, {{ quest.id }})">{{ quest.answer4 }}</button> {% else %}<button id="an" class="bttn btn btn-outline-warning" onclick="answer(4, {{ quest.id }})"></button>{% endif %}
                                    </div>
                                {% endif %}
                                {% if quest.questimg and not quest.quest %}
                                    <div id="questbttns">
                                        <button class="bttn btn btn-outline-warning" onclick="answer(1, {{ quest.id }})">1</button>
                                        <button class="bttn btn btn-outline-warning" onclick="answer(2, {{ quest.id }})">2</button>
                                        <button class="bttn btn btn-outline-warning" onclick="answer(3, {{ quest.id }})">3</button>
                                        <button class="bttn btn btn-outline-warning" onclick="answer(4, {{ quest.id }})">4</button>
                                    </div>
                                {% endif %}
                                <h6 id="an">{{ quest.answer }}</h6>
                            </div>
                        </li>
                        {% endfor %}
                    </ol>
                    <div>
                        <form id="homeworkform" method="POST" action="{% url 'reports:examrf' exam.id %}">
                            {% csrf_token %}
                            <input id="result" name="result" hidden value=""/>
                            <input id="wrong" name="wrong" hidden value=""/>
                            <input   id="questions" name="questions" hidden value=""/>
                            <input id="precentage" type="text" name="present" hidden value=""/>
                            <input class='bttn btn btn-outline-success' type="submit" value="ارسل الاجابات" />
                        </form>
                    </div>
                    {% else %}
                        <h1 class="not alert alert-danger">لم يتم نشر الإمتحان بعد </h1>
                        <a href="{% url 'tasks:exams' %}"> <-- عوده للإمتحانات</a>
                    {% endif %}
                {% endif %}
                {% if finish %}
                    <h1 class="not alert alert-danger">لقد قدمت هذا الاختبار من قبل </h1>
                    <a href="{% url 'tasks:exams' %}"> <-- عوده للإمتحانات</a>
                {% endif %}
        {% endif %}
        {% if user.is_staff %}
            {% if quest %}
                <ol id="exam-body">
                    {% for quest in quest %}
                        <li>
                            <div id="quest" class="quest{{quest.id}}">
                                {% if not quest.questimg %}
                                    <h3 class="ask">{{ quest.quest }}</h3>
                                {% else %}
                                    <img id="questimg" src="{{ quest.questimg.url }}" alt="{{quest}}" width="100%" />
                                {% endif %}
                                {% if quest.quest %}
                                    <div id="questbttns">
                                        {% if quest.answer1 %}<button class="bttn btn btn-outline-warning" onclick="answer(1, {{ quest.id }})">{{ quest.answer1 }}</button> {% else %}<button id="an" class="bttn btn btn-outline-warning" onclick="answer(1, {{ quest.id }})"></button>{% endif %}
                                        {% if quest.answer2 %}<button class="bttn btn btn-outline-warning" onclick="answer(2, {{ quest.id }})">{{ quest.answer2 }}</button> {% else %}<button id="an" class="bttn btn btn-outline-warning" onclick="answer(2, {{ quest.id }})"></button>{% endif %}
                                        {% if quest.answer3 %}<button class="bttn btn btn-outline-warning" onclick="answer(3, {{ quest.id }})">{{ quest.answer3 }}</button> {% else %}<button id="an" class="bttn btn btn-outline-warning" onclick="answer(3, {{ quest.id }})"></button>{% endif %}
                                        {% if quest.answer4 %}<button class="bttn btn btn-outline-warning" onclick="answer(4, {{ quest.id }})">{{ quest.answer4 }}</button> {% else %}<button id="an" class="bttn btn btn-outline-warning" onclick="answer(4, {{ quest.id }})"></button>{% endif %}
                                    </div>
                                {% endif %}
                                {% if quest.questimg %}
                                    <div id="questbttns">
                                        <button class="bttn btn btn-outline-warning" onclick="answer(1, {{ quest.id }})">1</button>
                                        <button class="bttn btn btn-outline-warning" onclick="answer(2, {{ quest.id }})">2</button>
                                        <button class="bttn btn btn-outline-warning" onclick="answer(3, {{ quest.id }})">3</button>
                                        <button class="bttn btn btn-outline-warning" onclick="answer(4, {{ quest.id }})">4</button>
                                    </div>
                                {% endif %}
                                <h6 id="an">{{ quest.answer }}</h6>
                            </div>
                        </li>
                    {% endfor %}
                </ol>
                <div>
                    <form id="homeworkform" method="POST" action="{% url 'reports:examrf' exam.id %}">
                        {% csrf_token %}
                        <input id="result" name="result" hidden value=""/>
                        <input id="wrong" name="wrong" hidden value=""/>
                        <input   id="questions" name="questions" hidden value=""/>
                        <input id="precentage" type="text" name="present" hidden value=""/>
                        <a class="btn btn-outline-success" href="{% url 'tasks:exams' %}"> <-- عوده للإمتحانات</a>
                    </form>
                </div>
            {% else %}
                <h1 class="not alert alert-danger">لم يتم نشر الامتحان بعد  </h1>
                <a href="{% url 'tasks:exams' %}"> <-- عوده للإمتحانات</a>
            {% endif %}
        {% endif %}
    </div>
{% endblock main %}
{% block spscript %}
    <script>
            window.addEventListener("load", function(){
                document.querySelectorAll(".nav-link")[0].classList.remove("active");
                document.querySelectorAll(".nav-link")[2].classList.add("active");
            });
        let correctanswers=0;
        let wronganswers=0;
        var res = document.getElementById("result");
        var wro = document.getElementById("wrong");
        let pres = document.getElementById("precentage");
        let quest = document.getElementById("questions");
        let present;
        let tasksnumber = 0;
        var btn = document.querySelectorAll(".bttn");
        {% for quest in quest %}
            var quest{{ quest.id }} = document.querySelector(".quest{{quest.id}}");
            tasksnumber++;
        {% endfor %}
        quest.value = tasksnumber;
            function answer(i, id) {
                let pre;
                var q = "quest" + id
                var ask = document.querySelector("."+q)
                var correct = ask.children[2].innerHTML
                ask.children[1].children[i-1].style.border="4px solid red"
                ask.children[1].children[i-1].style.textDecoration="3px line-through red"
                console.log(i)
                if (correct == i){
                    ask.children[1].children[0].setAttribute("disabled", true);
                    ask.children[1].children[1].setAttribute("disabled", true);
                    ask.children[1].children[2].setAttribute("disabled", true);
                    ask.children[1].children[3].setAttribute("disabled", true);
                    correctanswers ++;
                    res.value = correctanswers;
                    pre = (correctanswers / tasksnumber)*100;
                    finalpres = String(pre).split(".");
                    pres.value =String(finalpres[0])
                }
                else{
                    ask.children[1].children[0].setAttribute("disabled", true);
                    ask.children[1].children[1].setAttribute("disabled", true);
                    ask.children[1].children[2].setAttribute("disabled", true);
                    ask.children[1].children[3].setAttribute("disabled", true);
                    wronganswers ++;
                    wro.value =  wronganswers;
                    pre = (correctanswers / tasksnumber)*100;
                    finalpres = String(pre).split(".");
                    pres.value =String(finalpres[0])
                }
            }
            window.addEventListener("load", function(){
                document.querySelectorAll(".nav-link")[0].classList.remove("active");
                document.querySelectorAll(".nav-link")[2].classList.add("active");
            });
    </script>
{% endblock spscript %}

tasks/templates/tasks/exams.html
{% extends 'index.html' %}
{% block main %}
<header>
    <h6>{{ cuser }}</h6>
    <h1 class="ht">
        مرحبا بك يا {% if cuser.is_staff %} {{cuser.first_name}} {% else %} {{cuser.Sfname}} {% endif %} في مركزنا
        التعليمي
    </h1>
</header>
<h3>الامتحانات المنشوره:</h3>
<hr style="height:5px;" class="bg-warning">
{% if exams %}
<div class="row">
    <ol class="list-group list-group-numbered col-md-12">
        {% for exam in exams %}
        <a class="exam-link" href="{% url 'task:exam' exam.id %}">
            <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                <h1>{{ exam.title }}</h1>
                <span class="badge">{{ exam.publishAt }}</span>
            </li>
        </a>
        {% endfor %}
    </ol>
    <div>
        {% else %}
        <div class="row">
            <ol class="list-group list-group-numbered col-md-12">
                <a href='#'>
                    <li
                        class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                        <h1> لا يوجد امتحانات منشوره بعد</h1>
                    </li>
                </a>
                {% endif %}
            </ol>
            <div>
{% endblock main %}
{% block spscript %}
    <script>
        window.addEventListener("load", function(){
            document.querySelectorAll(".nav-link")[0].classList.remove("active");
            document.querySelectorAll(".nav-link")[2].classList.add("active");
        });
    </script>
{% endblock spscript %}

tasks/templates/tasks/homeworks.html
{% extends 'index.html' %}

{% block main %}
<div class="mt-3" id="exam">
    <h1 style="text-align:center; text-decoration:underline;"> الواجب المنزلي لدرس {{ les.name }} </h1>
    <hr style="height:10px; background-color:blue;">
    {% if not user.is_staff %}
            {% if ask %}
                {% if not flesh %}
                    <ol id="exam-body">
                        {% for ask in ask %}
                        <li>
                            <div id="quest" class="quest{{ask.id}}">
                                {% if not ask.questimg %}
                                <h3 class="ask">{{ ask.quest }}</h3>
                                {% else %}
                                <img id="questimg" src="{{ ask.questimg.url }}" alt="{{ask}}" width="100%" />
                                {% endif %}
                                {% if ask.quest %}
                                <div id="questbttns">
                                    {% if ask.answer1 %}<button class="bttn btn btn-outline-warning"
                                        onclick="answer(1, {{ ask.id }})">{{ ask.answer1 }}</button> {% else %}<button id="an"
                                        class="bttn btn btn-outline-warning" onclick="answer(1, {{ ask.id }})"></button>{% endif %}
                                    {% if ask.answer2 %}<button class="bttn btn btn-outline-warning"
                                        onclick="answer(2, {{ ask.id }})">{{ ask.answer2 }}</button> {% else %}<button id="an"
                                        class="bttn btn btn-outline-warning" onclick="answer(2, {{ ask.id }})"></button>{% endif %}
                                    {% if ask.answer3 %}<button class="bttn btn btn-outline-warning"
                                        onclick="answer(3, {{ ask.id }})">{{ ask.answer3 }}</button> {% else %}<button id="an"
                                        class="bttn btn btn-outline-warning" onclick="answer(3, {{ ask.id }})"></button>{% endif %}
                                    {% if ask.answer4 %}<button class="bttn btn btn-outline-warning"
                                        onclick="answer(4, {{ ask.id }})">{{ ask.answer4 }}</button> {% else %}<button id="an"
                                        class="bttn btn btn-outline-warning" onclick="answer(4, {{ ask.id }})"></button>{% endif %}
                                </div>
                                {% endif %}
                                {% if quest.questimg %}
                                <div id="questbttns">
                                    <button class="bttn btn btn-outline-warning" onclick="answer(1, {{ quest.id }})">1</button>
                                    <button class="bttn btn btn-outline-warning" onclick="answer(2, {{ quest.id }})">2</button>
                                    <button class="bttn btn btn-outline-warning" onclick="answer(3, {{ quest.id }})">3</button>
                                    <button class="bttn btn btn-outline-warning" onclick="answer(4, {{ quest.id }})">4</button>
                                </div>
                                {% endif %}
                                <h6 id="an">{{ ask.answer }}</h6>
                                <i id="sr"></i>
                            </div>
                        </li>
                        {% endfor %}
                    </ol>
                    <div>
                        <h1>التقرير</h1>
                        <hr>
                        <h2> اجابات صحيحه :  <span id="resultt"> </span> </h2>
                        <h2> اجابات خاطئه :  <span id="wrongt"> </span> </h2>
                        <h2> عدد الاسئله :  <span id="questt"> </span> </h2>
                        <h2> النسبه المئويه :  <span id="percentt"> </span> </h2>
                        <form id="homeworkform" method="POST" action="{% url 'reports:homerf' les.id %}">
                            {% csrf_token %}
                            <input id="result" name="result" hidden value="" />
                            <input id="wrong" name="wrong" hidden value="" />
                            <input id="questions" name="questions" hidden value="" />
                            <input id="precentage" type="text" name="present" hidden value="" />
                            <input class='btn btn-outline-success' type="submit" value="ارسل الاجابات" />
                        </form>
                    </div>
                {% else %}
                    <h1 class="not alert alert-danger">لقد قدمت هذا الواجب بالفعل </h1>
                    <a href="{% url 'home:lesson' les.id %}">
                        <-- عوده للدرس</a>
                {% endif %}
            {% else %}
                <h1 class="not alert alert-danger">لا يوجد واجب منزلي لهذا الدرس
                </h1>
                <a href="{% url 'home:lesson' les.id %}">
                    <-- عوده للدرس</a>
            {% endif %}
    {% endif %}
    {% if user.is_staff %}
            {% if ask %}
                <ol id="exam-body">
                    {% for ask in ask %}
                    <li>
                        <div id="quest" class="quest{{ask.id}}">
                            {% if not ask.questimg %}
                                <h3 class="ask">{{ ask.quest }}</h3>
                            {% else %}
                                <img src="{{ ask.questimg.url }}" alt="{{ask}}" width="200" />
                            {% endif %}
                            {% if ask.quest %}
                                <div id="questbttns">
                                    {% if ask.answer1 %}<button class="bttn btn btn-outline-warning"
                                        onclick="answer(1, {{ ask.id }})">{{ ask.answer1 }}</button> {% else %}<button
                                        id="an" class="bttn btn btn-outline-warning"
                                        onclick="answer(1, {{ ask.id }})"></button>{% endif %}
                                    {% if ask.answer2 %}<button class="bttn btn btn-outline-warning"
                                        onclick="answer(2, {{ ask.id }})">{{ ask.answer2 }}</button> {% else %}<button
                                        id="an" class="bttn btn btn-outline-warning"
                                        onclick="answer(2, {{ ask.id }})"></button>{% endif %}
                                    {% if ask.answer3 %}<button class="bttn btn btn-outline-warning"
                                        onclick="answer(3, {{ ask.id }})">{{ ask.answer3 }}</button> {% else %}<button
                                        id="an" class="bttn btn btn-outline-warning"
                                        onclick="answer(3, {{ ask.id }})"></button>{% endif %}
                                    {% if ask.answer4 %}<button class="bttn btn btn-outline-warning"
                                        onclick="answer(4, {{ ask.id }})">{{ ask.answer4 }}</button> {% else %}<button
                                        id="an" class="bttn btn btn-outline-warning"
                                        onclick="answer(4, {{ ask.id }})"></button>{% endif %}
                                </div>
                            {% endif %}
                            {% if quest.questimg %}
                                <div id="questbttns">
                                    <button class="bttn btn btn-outline-warning"
                                        onclick="answer(1, {{ quest.id }})">1</button>
                                    <button class="bttn btn btn-outline-warning"
                                        onclick="answer(2, {{ quest.id }})">2</button>
                                    <button class="bttn btn btn-outline-warning"
                                        onclick="answer(3, {{ quest.id }})">3</button>
                                    <button class="bttn btn btn-outline-warning"
                                        onclick="answer(4, {{ quest.id }})">4</button>
                                </div>
                            {% endif %}
                            <h6 id="an">{{ ask.answer }}</h6>
                            <i id="sr"></i>
                        </div>
                    </li>
                    {% endfor %}
                    </ol>
                    <div>
                        <h1>التقرير</h1>
                        <hr>
                        <h2> اجابات صحيحه :  <span id="resultt"> </span> </h2>
                    <h2> اجابات خاطئه :  <span id="wrongt"> </span> </h2>
                    <h2> عدد الاسئله :  <span id="questt"> </span> </h2>
                    <h2> النسبه المئويه :  <span id="percentt"> </span> </h2>
                        <form id="homeworkform" method="POST" action="{% url 'reports:homerf' les.id %}">

                            </ol>
                            <div>
                                <h1>التقرير</h1>
                                <hr>
                                <input hidden id="result" name="result" value="" />
                                <input hidden id="wrong" name="wrong" value="" />
                                <input hidden id="questions" name="questions" value="" />
                                <input hidden id="precentage" type="text" name="present" value="" />
                                <a class='btn btn-outline-success' href="{% url 'home:lesson' les.id %}">عوده للدرس --></a>
                {% else %}
                    <h1 class="not alert alert-danger">لا يوجد واجب منزلي لهذا الدرس
                    </h1>
                    <a href="{% url 'home:lesson' les.id %}">
                    <-- عوده للدرس</a>
            {% endif %}
    {% endif %}
    {% endblock main %}
    {% block spscript %}
        <script>
    window.addEventListener("load", function(){
        document.querySelectorAll(".nav-link")[0].classList.remove("active");
        document.querySelectorAll(".nav-link")[1].classList.add("active");
    });
    let correctanswers=0;
    let wronganswers=0;
    var res = document.getElementById("result");
    var wro = document.getElementById("wrong");
    var homeform = document.getElementById("homeworkform");
    let pres = document.getElementById("precentage");
    let quest = document.getElementById("questions");
    let present;
    let tasksnumber = 0;
    var btn = document.querySelectorAll(".bttn");
    var resultt = document.getElementById("resultt");
    var wrongt = document.getElementById("wrongt");
    var questt = document.getElementById("questt");
    var percentt = document.getElementById("percentt");
    let finalpres=0;
    var nfinalpres = 0;

    {% for ask in ask %}
    var quest{{ ask.id }} = document.querySelector(".quest{{ask.id}}");
    tasksnumber++;
    {% endfor %}
    quest.value = tasksnumber;
    questt.innerHTML += tasksnumber;

    function answer(i, id) {
        let pre;
        var q = "quest" + id
        var ask = document.querySelectorAll("."+q)[0];


        var correct = ask.children[2].innerHTML;
        ask.children[1].children[i-1].style.border="4px solid red"
        ask.children[1].children[i-1].style.textDecoration="3px line-through red"
        if (correct == i){
        console.log()
        ask.children[3].classList.add("bi" ,"bi-check-circle-fill");
        ask.children[1].children[0].setAttribute("disabled", true);
        ask.children[1].children[1].setAttribute("disabled", true);
        ask.children[1].children[2].setAttribute("disabled", true);
        ask.children[1].children[3].setAttribute("disabled", true);
        correctanswers ++;
        res.value = correctanswers;
        resultt.innerHTML = correctanswers;
        pre = (correctanswers / tasksnumber)*100;
        finalpres = String(pre).split(".");
        nfinalpres = Number(finalpres[0]);
        pres.value = String(nfinalpres) + "%";
        percentt.innerHTML = String(nfinalpres) + "%";
        }
        else{
        ask.children[3].classList.add("bi" ,"bi-x-circle-fill");
        ask.children[1].children[0].setAttribute("disabled", true);
        ask.children[1].children[1].setAttribute("disabled", true);
        ask.children[1].children[2].setAttribute("disabled", true);
        ask.children[1].children[3].setAttribute("disabled", true);
        wronganswers ++;
        wro.value = wronganswers;
        wrongt.innerHTML = wronganswers;
        pre = (correctanswers / tasksnumber)*100;
        finalpres = String(pre).split(".");
        nfinalpres = Number(finalpres[0]);
        pres.value = String(nfinalpres) + "%";
        percentt.innerHTML = String(nfinalpres) + "%";
        }
        }

        </script>
        {% endblock spscript %}